### PR TITLE
Fix #88: Add license information.

### LINKED ISSUE #88: POM: Missing license information
We use Sonatype IQ Server and its reporting all Jackson JARs as missing their license info.  This is a simple fix add this section to your base pom.xml which is inherited by all your JARS.

```xml
	<licenses>
		<license>
			<name>Apache 2</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
			<comments>A business-friendly OSS license</comments>
		</license>
	</licenses>
```

**Sonatype screenshot showing warnings:**
image

### PR DESCRIPTION
**Pull request by melloware**
Hopefully you can migrate this to the 2.9 and 2.10 branches as well?

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Why? Information is already available from base pom, and now in repos too.

**Comment by melloware** [comment]
I will report this issue to Sonatype and let you know what they say!

**Comment by melloware** [comment]
Its the goofy way Sonatype reports license issues.  You are doing exactly the right thing already. Closing ticket.

**Comment by cowtowncoder** [comment]
Ok thank you for following up!

**Pull request closed without merging**
