### PR TITLE
Adding ppc64le architecture support

### PR DESCRIPTION
**Pull request by kishorkunal-raj**
Hi,
I had added ppc64le support and looks like its been successfully added. I believe it is ready for the final review and merge.

The travis ci build logs can be verified from the link below.
https://www.travis-ci.com/github/kishorkunal-raj/jackson-modules-base/builds/181457864
Please have a look.

Thanks!!"

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@kishorkunal-raj Could you remind of the specific need for this?

Also curious as to details: why is specific version of Maven needed as override here?

**Comment by Siddhesh-Ghadi** [comment]
> Also curious as to details: why is specific version of Maven needed as override here?

There is no specific version needed, its just that there is no default maven package present for ppc64le on travis and we need to manually install it. That being said, we are working on getting maven added has default package on travis for ppc64le so that there is not need to install it manually.

**Comment by gerrith3** [comment]
This package is included in the ppc64le versions of RHEL and Ubuntu - this allows the top of tree to be tested continuously as it is for Intel, making it easier to catch any possible regressions on ppc64le before the distros begin their clones and builds.  This reduces the work in integrating this package into future versions of RHEL/Ubuntu.

**Comment by cowtowncoder** [comment]
Ok thank you -- presumably problems with Afterburner, primarily?
I am mostly curious about actual observed issues, given that this a Java project.

**Comment by cowtowncoder** [comment]
@Siddhesh-Ghadi ah. That makes sense (wrt inclusion lacking). I can add this for now, but if situation changes would be nice to remove installation instruction (although maybe check to see version exists means it does not add much to build time).

**Pull request merged**
