### PR TITLE
(nit) unnecessary logic, better readability

### PR DESCRIPTION
**Pull request by chtompki**

### CODE REVIEW

**Comment by chtompki** [comment]
I expect the build to succeed on the jaxb module, but fail on the Afterburner module as that was the current state of the master branch during the work on this PR.

**Comment by cowtowncoder** [comment]
Thanks. Might make sense to apply for `2.9` branch, I can merge forward?

**Comment by chtompki** [comment]
@cowtowncoder - I'm ok with whatever you want to do with it. I just happened to be in there the other day and figured it could be simplified.

**Comment by cowtowncoder** [comment]
@chtompki Yes, much appreciated. Code must have morphed through some refactoring as it makes little sense as is :)

**Pull request merged**
