### PR TITLE
bumb jakarta.activation-api to 1.2.2

### PR DESCRIPTION
**Pull request by bsanchezb**
Hello,

Please update jakarta api version within the project for the next release version.

Regards,
Aleksandr.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Any specific fixes, problems this helps with @bsanchezb ?

@GedMarc any concerns?

**Comment by bsanchezb** [comment]
Hello @cowtowncoder,

Another dependency in our project has been upgraded to 1.2.2 version (Apache Santuario using a transitive dependency). Because of the conflict with jackson dependency, we have to force the version of jakarta to be 1.2.2 in our pom.xml.
We would like to have all our project dependencies using the same version of jakarta to avoid compliancy issues.

The new release of jakarta is a minor one, so it does not hurt to my opinion. But you can always verify whether it is applicable for your project.

Best regards,
Aleksandr.

**Comment by GedMarc** [comment]
Confirmed activation is safe - no removals or deprecations, have tested with 2.13.0 successfully

**Review by GedMarc — APPROVED** [review]

**Comment by bsanchezb** [comment]
Thank you!

Regards,
Aleksandr.

**Pull request merged**
